(function(root){
  'use strict';
  var SCHEMA_VERSION=1;
  var DEFAULT_POLICY={minTransferMinutes:15,maxPreferredWaitMinutes:60,idealWaitMinutes:30,minReliabilityScore:0};
  function num(v,fallback){var n=Number(v);return isFinite(n)?n:fallback;}
  function clean(v){return String(v==null?'':v).trim();}
  function timeToMinutes(v){var m=clean(v).match(/^(\d{1,2}):(\d{2})$/);if(!m)return null;var h=Number(m[1]),n=Number(m[2]);return h>=0&&h<24&&n>=0&&n<60?h*60+n:null;}
  function forwardDiff(from,to){if(from===null||to===null)return null;var d=to-from;return d<0?d+1440:d;}
  function stopOrder(stops){return Object.keys(stops||{}).filter(function(k){var s=stops[k]||{};return s.bookingEnabled!==false&&(s.networkRole==='main'||s.stopType==='main'||s.stopType==='transfer_hub');}).sort(function(a,b){return num(stops[a]&&stops[a].order,999999)-num(stops[b]&&stops[b].order,999999)||a.localeCompare(b);});}
  function groupType(g){var t=clean(g&&g.connectionType).toLowerCase();if(t==='transfer'||t==='branch')return'branch';return'main';}
  function hubKey(g){return clean(g&&(g.branchHubStopKey||g.transferHubStopKey));}
  function groupPolicy(g,base){base=Object.assign({},DEFAULT_POLICY,base||{});return{minTransferMinutes:num(g&&g.minTransferMinutes,base.minTransferMinutes),maxPreferredWaitMinutes:num(g&&g.maxPreferredWaitMinutes,base.maxPreferredWaitMinutes),idealWaitMinutes:num(g&&g.idealWaitMinutes,base.idealWaitMinutes),reliabilityScore:num(g&&g.reliabilityScore,100),priority:num(g&&g.recommendationPriority,100),passengerChoiceEnabled:g&&g.passengerChoiceEnabled!==false};}
  function normalizeGroups(groups){return Object.keys(groups||{}).map(function(key){var g=groups[key]||{};return{key:key,id:clean(g.id||key),name:clean(g.name||key),type:groupType(g),hubStopKey:hubKey(g),isActive:g.isActive!==false,policy:groupPolicy(g),routes:Array.isArray(g.routes)?g.routes:[]};});}
  function validateAdminData(input){input=input||{};var stops=input.stops||{},main=stopOrder(stops),groups=normalizeGroups(input.groups||input.routes||{}),errors=[],warnings=[],seen={};groups.forEach(function(g){if(seen[g.id])errors.push('group_id ซ้ำ: '+g.id);seen[g.id]=true;if(g.type==='branch'){if(!g.hubStopKey)errors.push('กลุ่ม '+g.name+' ยังไม่ระบุรหัสจุดต่อรถ');else if(main.indexOf(g.hubStopKey)===-1)errors.push('จุดต่อรถ '+g.hubStopKey+' ของกลุ่ม '+g.name+' ไม่อยู่ในเส้นทางหลัก');if(g.policy.minTransferMinutes<0)errors.push('เวลาเปลี่ยนรถขั้นต่ำของ '+g.name+' ไม่ถูกต้อง');if(g.policy.maxPreferredWaitMinutes<g.policy.minTransferMinutes)errors.push('เวลารอสูงสุดของ '+g.name+' ต้องไม่น้อยกว่าเวลาเปลี่ยนรถขั้นต่ำ');}g.routes.forEach(function(r){if(r.isActive===false)return;if(!clean(r.toStopKey||r.to))warnings.push('กลุ่ม '+g.name+' มีเส้นทางที่ยังไม่มีปลายทาง');});});return{valid:errors.length===0,schemaVersion:SCHEMA_VERSION,mainStopKeys:main,groups:groups,errors:errors,warnings:warnings};}
  function isJourneyAllowed(origin,destination,mainStopKeys,destinationGroups){var main={};(mainStopKeys||[]).forEach(function(k){main[k]=true;});var a=!!main[origin],b=!!main[destination];if(a&&b)return true;if(a&&!b)return !!(destinationGroups&&destinationGroups[destination]&&destinationGroups[destination].length);if(!a&&b)return false;return false;}
  function riskFor(wait,policy){if(wait===null)return{level:'unavailable',reason:'missing_time'};if(wait<0)return{level:'unavailable',reason:'departed'};if(wait<policy.minTransferMinutes)return{level:'high',reason:'short_transfer'};if(wait>policy.maxPreferredWaitMinutes)return{level:'long_wait',reason:'long_wait'};return{level:'low',reason:'safe_wait'};}
  function rankTransferOptions(options,policy){policy=Object.assign({},DEFAULT_POLICY,policy||{});return(options||[]).map(function(raw){var p=Object.assign({},policy,raw.policy||{}),arr=timeToMinutes(raw.arrivalHubTime),dep=timeToMinutes(raw.leg2DepartureTime),fin=timeToMinutes(raw.finalArrivalTime),wait=forwardDiff(arr,dep),risk=riskFor(wait,p),available=raw.active!==false&&raw.reachable!==false&&risk.level!=='unavailable';var tier=!available?9:(risk.level==='low'?0:(risk.level==='long_wait'?1:2));return Object.assign({},raw,{transferWaitMinutes:wait,riskLevel:risk.level,riskReason:risk.reason,available:available,_tier:tier,_final:fin===null?999999:fin,_idealDistance:wait===null?999999:Math.abs(wait-p.idealWaitMinutes),_reliability:num(raw.reliabilityScore,p.reliabilityScore),_priority:num(raw.recommendationPriority,p.priority),_hubArrival:arr===null?999999:arr});}).sort(function(a,b){return a._tier-b._tier||a._final-b._final||b._reliability-a._reliability||a._idealDistance-b._idealDistance||a._hubArrival-b._hubArrival||a._priority-b._priority||String(a.groupId||'').localeCompare(String(b.groupId||''));}).map(function(x,index){var out=Object.assign({},x);delete out._tier;delete out._final;delete out._idealDistance;delete out._reliability;delete out._priority;delete out._hubArrival;out.recommended=index===0&&out.available&&out.riskLevel!=='high';return out;});}
  function buildTransferCandidates(input){input=input||{};var main=input.mainStopKeys||[],origin=clean(input.originStopKey),destination=clean(input.destinationStopKey),groups=input.destinationGroups||{};if(!isJourneyAllowed(origin,destination,main,groups))return[];var targetGroups=groups[destination]||[],leg1=input.leg1Options||[],leg2=input.leg2Options||[],out=[];targetGroups.forEach(function(g){var hub=clean(g.hubStopKey),policy=groupPolicy(g,input.policy);leg1.filter(function(a){return clean(a.toStopKey)===hub&&a.active!==false;}).forEach(function(a){leg2.filter(function(b){return clean(b.groupId)===clean(g.groupId||g.id)&&clean(b.fromStopKey)===hub&&b.active!==false;}).forEach(function(b){out.push({groupId:clean(g.groupId||g.id),groupName:g.name||'',hubStopKey:hub,leg1TripId:a.tripId||'',leg2TripId:b.tripId||'',arrivalHubTime:a.arrivalTime||'',leg2DepartureTime:b.departureTime||'',finalArrivalTime:b.arrivalTime||'',active:true,reachable:true,reliabilityScore:b.reliabilityScore,policy:policy,passengerChoiceEnabled:policy.passengerChoiceEnabled});});});});return rankTransferOptions(out,input.policy);}
  var api={schemaVersion:SCHEMA_VERSION,defaultPolicy:Object.assign({},DEFAULT_POLICY),stopOrder:stopOrder,normalizeGroups:normalizeGroups,validateAdminData:validateAdminData,isJourneyAllowed:isJourneyAllowed,rankTransferOptions:rankTransferOptions,buildTransferCandidates:buildTransferCandidates,timeToMinutes:timeToMinutes};
  root.SLTransitNetwork=api;
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);