const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '..', 'admin-erp.html'), 'utf8');
const legacyAdmin = fs.readFileSync(path.join(__dirname, '..', 'admin.html'), 'utf8');
const compatibilityAdmin = fs.readFileSync(path.join(__dirname, '..', 'admin-console.html'), 'utf8');

assert.ok(html.includes("projectId: 'sl-transit-9464e'"));
assert.ok(html.includes("databaseURL: 'https://sl-transit-9464e-default-rtdb.asia-southeast1.firebasedatabase.app'"));
assert.ok(html.includes("var PUBLISHED_SCHEDULE_PATH = 'preview/publishedSchedule';"));
assert.ok(html.includes('bus-booking-1d68c not used'));
assert.ok(!/projectId:\s*['"]bus-booking-1d68c['"]/.test(html));
assert.ok(!/\.ref\([^)]*\)\.(set|update|push|remove)\s*\(/.test(html));
assert.ok(!/\.ref\([^)]*routeData[^)]*\)\.(set|update|push|remove)\s*\(/.test(html));
assert.ok(!/\.ref\([^)]*settings\/routes[^)]*\)\.(set|update|push|remove)\s*\(/.test(html));
assert.ok(!/\.ref\([^)]*routes[^)]*\)\.(set|update|push|remove)\s*\(/.test(html));
assert.ok(html.includes('ERP_SOURCE_REGISTRY'));
assert.ok(html.includes('CENTER_STATUS_RULES'));
assert.ok(html.includes('centerStatusPackage'));
assert.ok(html.includes('downloadCenterStatus'));
assert.ok(html.includes('MODULE_REGISTRY'));
assert.ok(html.includes('moduleStatusPackage'));
assert.ok(html.includes('downloadModuleStatus'));
assert.ok(html.includes('sl-transit-admin-module-status.json'));
assert.ok(html.includes('blockedScope'));
assert.ok(html.includes('allowedScope'));
assert.ok(html.includes('mapValidationPackage'));
assert.ok(html.includes('downloadMapValidation'));
assert.ok(html.includes('sl-transit-admin-map-validation.json'));
assert.ok(html.includes('expectedStops:15'));
assert.ok(html.includes('fakeGps:false'));
assert.ok(html.includes('fakeEta:false'));
assert.ok(html.includes('routeFareTimetableValidationPackage'));
assert.ok(html.includes('downloadRouteFareTimetableValidation'));
assert.ok(html.includes('sl-transit-admin-route-fare-timetable-validation.json'));
assert.ok(html.includes('paymentTouched:false'));
assert.ok(html.includes('liveVehicleTouched:false'));
assert.ok(html.includes('calculatorValidationPackage'));
assert.ok(html.includes('downloadCalculatorValidation'));
assert.ok(html.includes('sl-transit-admin-calculator-validation.json'));
assert.ok(html.includes('erp-calculator-center.js'));
assert.ok(html.includes('fakeEta:false'));
assert.ok(html.includes('fakeGps:false'));
assert.ok(html.includes('opsMasterValidationPackage'));
assert.ok(html.includes('downloadOpsMasterValidation'));
assert.ok(html.includes('sl-transit-admin-ops-master-validation.json'));
assert.ok(html.includes('driverRuntimeTouched:false'));
assert.ok(html.includes('fakeDriver:false'));
assert.ok(html.includes('fakeVehicle:false'));
assert.ok(html.includes('fakeAssignment:false'));
assert.ok(html.includes('policyLogicValidationPackage'));
assert.ok(html.includes('downloadPolicyLogicValidation'));
assert.ok(html.includes('sl-transit-admin-policy-logic-validation.json'));
assert.ok(html.includes('bookingsTouched:false'));
assert.ok(html.includes('ticketsTouched:false'));
assert.ok(html.includes('passengersTouched:false'));
assert.ok(html.includes('ANNOUNCEMENT_CATEGORIES'));
assert.ok(html.includes('announcementPlanPackage'));
assert.ok(html.includes('downloadAnnouncementPlan'));
assert.ok(html.includes('sl-transit-admin-announcement-plan.json'));
assert.ok(html.includes('lineSending:false'));
assert.ok(html.includes('pushNotification:false'));
assert.ok(html.includes('erp-data-adapter.js'));
assert.ok(html.includes('erp-engine.js'));
assert.ok(html.includes('erp-calculator-center.js'));
assert.ok(html.includes('erp-alert-center.js'));
assert.ok(html.includes('map-display-center.js'));
assert.ok(html.includes('erp-admin-master-data.js'));
assert.ok(html.includes('localEdits'));
assert.ok(html.includes('workbookHash'));
assert.ok(html.includes('hashPayload'));
assert.ok(html.includes('REQUIRED_SHEET_COUNT'));
assert.ok(html.includes('sheetReadinessPackage'));
assert.ok(html.includes('downloadSheetReadiness'));
assert.ok(html.includes('missingRequiredSheets'));
assert.ok(html.includes('draftPackage'));
assert.ok(html.includes('candidatePublishedSchedule'));
assert.ok(html.includes('ADMIN_FILE_REGISTRY'));
assert.ok(html.includes('adminAuditPackage'));
assert.ok(html.includes('downloadAdminAudit'));
assert.ok(html.includes('auditEvents'));
assert.ok(html.includes('recordAudit'));
assert.ok(html.includes('auditLogPackage'));
assert.ok(html.includes('downloadLocalAuditLog'));
assert.ok(html.includes('sl-transit-admin-local-audit-log.json'));
assert.ok(html.includes('eventCount'));
assert.ok(html.includes('REVIEW_ARTIFACTS'));
assert.ok(html.includes('FUTURE_RULE_REQUIREMENTS'));
assert.ok(html.includes('rulesRequirementsPackage'));
assert.ok(html.includes('downloadRulesRequirements'));
assert.ok(html.includes('releaseManifest'));
assert.ok(html.includes('downloadReleaseManifest'));
assert.ok(html.includes('readinessSummaryPackage'));
assert.ok(html.includes('downloadReadinessSummary'));
assert.ok(html.includes('sl-transit-admin-readiness-summary.json'));
assert.ok(html.includes('waitingModules'));
assert.ok(html.includes('artifactCount'));
assert.ok(html.includes('ROLE_ACCESS_MATRIX'));
assert.ok(html.includes('roleAccessMatrixPackage'));
assert.ok(html.includes('downloadRoleAccessMatrix'));
assert.ok(html.includes('sl-transit-admin-role-access-matrix.json'));
assert.ok(html.includes('userRoleMutation:false'));
assert.ok(html.includes('releaseEvidence'));
assert.ok(html.includes('releaseEvidencePackage'));
assert.ok(html.includes('releaseEvidencePanel'));
assert.ok(html.includes('saveReleaseEvidence'));
assert.ok(html.includes('downloadReleaseEvidence'));
assert.ok(html.includes('sl-transit-admin-release-evidence.json'));
assert.ok(html.includes('backupRef'));
assert.ok(html.includes('rollbackNote'));
assert.ok(html.includes('rulesReviewRef'));
assert.ok(html.includes('reviewArtifacts'));
assert.ok(html.includes('reviewBundle'));
assert.ok(html.includes('downloadReviewBundle'));
assert.ok(html.includes('publishPlan'));
assert.ok(html.includes('releaseAssessment'));
assert.ok(html.includes('readinessScore'));
assert.ok(html.includes('blockedReasons'));
assert.ok(html.includes('applyAllowed:false'));
assert.ok(html.includes('releaseChecks'));
assert.ok(html.includes('ownerDecision'));
assert.ok(html.includes('ownerDecisionPanel'));
assert.ok(html.includes('saveOwnerDecision'));
assert.ok(html.includes('approved_for_future_apply'));
assert.ok(html.includes('ownerApproval'));
assert.ok(html.includes('freshBackup'));
assert.ok(html.includes('rollbackPlan'));
assert.ok(html.includes('firebaseRulesReview'));
assert.ok(html.includes('data-release-check'));
assert.ok(html.includes('sl-transit-admin-draft-package.json'));
assert.ok(html.includes('sl-transit-admin-file-audit.json'));
assert.ok(html.includes('sl-transit-admin-rules-requirements.json'));
assert.ok(html.includes('sl-transit-admin-center-status.json'));
assert.ok(html.includes('sl-transit-admin-candidate-publishedSchedule.json'));
assert.ok(html.includes('sl-transit-admin-sheet-readiness.json'));
assert.ok(html.includes('sl-transit-admin-release-manifest.json'));
assert.ok(html.includes('sl-transit-admin-review-bundle.json'));
assert.ok(html.includes('sl-transit-admin-blocked-publish-plan.json'));
assert.ok(html.includes("publicationStatus:'review_candidate_blocked'"));
assert.ok(html.includes('containsOperationalPrivateData:false'));
assert.ok(html.includes('deployRules:false'));
assert.ok(html.includes('mustNotDeployFromConsole:true'));
assert.ok(html.includes("primaryFile: 'admin-erp.html'"));
assert.ok(html.includes("legacyFile: 'admin.html'"));
assert.ok(html.includes("compatibilityRedirect: 'admin-console.html'"));
assert.ok(html.includes("['admin-erp.html','primary Admin Console'"));
assert.ok(html.includes("['admin.html','legacy redirect'"));
assert.ok(html.includes("['admin-console.html','compatibility redirect'"));
assert.ok(html.includes('FLOW_STEPS'));
assert.ok(html.includes('Excel'));
assert.ok(html.includes('Draft'));
assert.ok(html.includes('Review'));
assert.ok(html.includes('Publish'));
assert.ok(legacyAdmin.includes('url=admin-erp.html'));
assert.ok(compatibilityAdmin.includes('url=admin-erp.html'));

console.log('admin-erp safety ok');
