const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '..', 'admin-erp.html'), 'utf8');
const legacyAdmin = fs.readFileSync(path.join(__dirname, '..', 'admin.html'), 'utf8');
const compatibilityAdmin = fs.readFileSync(path.join(__dirname, '..', 'admin-console.html'), 'utf8');

aassert.ok(html.includes("projectId: 'sl-transit-9464e'"));
aassert.ok(html.includes("databaseURL: 'https://sl-transit-9464e-default-rtdb.asia-southeast1.firebasedatabase.app'"));
aassert.ok(html.includes("var PRIMARY_PUBLISHED_SCHEDULE_PATH = 'publishedSchedule';"));
aassert.ok(html.includes("var PREVIEW_PUBLISHED_SCHEDULE_PATH = 'preview/publishedSchedule';"));
aassert.ok(html.includes("var PUBLISHED_SCHEDULE_PATH = PRIMARY_PUBLISHED_SCHEDULE_PATH;"));
aassert.ok(html.includes('activeReadPath'));
aassert.ok(html.includes('fallbackReadPath'));
aassert.ok(html.includes('bus-booking-1d68c not used'));
aassert.ok(!/projectId:\s*['"]bus-booking-1d68c['"]/.test(html));
aassert.ok(html.includes('firebase-database-compat.js'));
aassert.ok(html.includes('function erpFareAuditAndWrite'));
aassert.ok(html.includes("data/erpDataCenter/meta/audit"));
aassert.ok(html.includes("data/erpDataCenter/workbookSource/routeFareRows"));
aassert.ok(html.includes("data/erpDataCenter/workbookSource/scheduleRows"));
aassert.ok(html.includes('function saveErpSchedule'));
aassert.ok(html.includes('function enterpriseScheduleEditor'));
const directFareWrites = html.match(/database\.ref\([^)]*\)\.(set|update|push|remove)\s*\(/g) || [];
assert.deepStrictEqual(directFareWrites.sort(), [
  "database.ref('data/erpDataCenter/meta/audit').push(",
  "database.ref('data/erpDataCenter/meta/audit').push(",
  'database.ref(path).set(',
  'database.ref(path).set('
].sort(), 'Admin ERP direct writes include audit-first fare, schedule, and queue updates');assert.ok(!/\.ref\([^)]*routeData[^)]*\)\.(set|update|push|remove)\s*\(/.test(html));
aassert.ok(!/\.ref\([^)]*settings\/routes[^)]*\)\.(set|update|push|remove)\s*\(/.test(html));
aassert.ok(!/\.ref\([^)]*routes[^)]*\)\.(set|update|push|remove)\s*\(/.test(html));
aassert.ok(html.includes('ERP_SOURCE_REGISTRY'));
aassert.ok(html.includes('CENTER_STATUS_RULES'));
aassert.ok(html.includes('centerStatusPackage'));
aassert.ok(html.includes('downloadCenterStatus'));
aassert.ok(html.includes('MODULE_REGISTRY'));
aassert.ok(html.includes('moduleStatusPackage'));
aassert.ok(html.includes('downloadModuleStatus'));
aassert.ok(html.includes('sl-transit-admin-module-status.json'));
aassert.ok(html.includes('blockedScope'));
aassert.ok(html.includes('allowedScope'));
aassert.ok(html.includes('mapValidationPackage'));
aassert.ok(html.includes('downloadMapValidation'));
aassert.ok(html.includes('sl-transit-admin-map-validation.json'));
aassert.ok(html.includes('expectedStops:15'));
aassert.ok(html.includes('fakeGps:false'));
aassert.ok(html.includes('fakeEta:false'));
aassert.ok(html.includes('routeFareTimetableValidationPackage'));
aassert.ok(html.includes('erp-workbook-source-contract.js'));
aassert.ok(html.includes('workbookSourceCandidate'));
aassert.ok(html.includes("erpDataCenterTargetPath:'/data/erpDataCenter/workbookSource'"));
aassert.ok(html.includes('workbookRouteFareRows'));
aassert.ok(html.includes('workbookScheduleRows'));
aassert.ok(html.includes('downloadRouteFareTimetableValidation'));
aassert.ok(html.includes('sl-transit-admin-route-fare-timetable-validation.json'));
aassert.ok(html.includes('paymentTouched:false'));
aassert.ok(html.includes('liveVehicleTouched:false'));
aassert.ok(html.includes('calculatorValidationPackage'));
aassert.ok(html.includes('downloadCalculatorValidation'));
aassert.ok(html.includes('sl-transit-admin-calculator-validation.json'));
aassert.ok(html.includes('erp-calculator-center.js'));
aassert.ok(html.includes('fakeEta:false'));
aassert.ok(html.includes('fakeGps:false'));
aassert.ok(html.includes('opsMasterValidationPackage'));
aassert.ok(html.includes('downloadOpsMasterValidation'));
aassert.ok(html.includes('sl-transit-admin-ops-master-validation.json'));
aassert.ok(html.includes('driverRuntimeTouched:false'));
aassert.ok(html.includes('fakeDriver:false'));
aassert.ok(html.includes('fakeVehicle:false'));
aassert.ok(html.includes('fakeAssignment:false'));
aassert.ok(html.includes('policyLogicValidationPackage'));
aassert.ok(html.includes('downloadPolicyLogicValidation'));
aassert.ok(html.includes('sl-transit-admin-policy-logic-validation.json'));
aassert.ok(html.includes('bookingsTouched:false'));
aassert.ok(html.includes('ticketsTouched:false'));
aassert.ok(html.includes('passengersTouched:false'));
aassert.ok(html.includes('ANNOUNCEMENT_CATEGORIES'));
aassert.ok(html.includes('announcementPlanPackage'));
aassert.ok(html.includes('downloadAnnouncementPlan'));
aassert.ok(html.includes('sl-transit-admin-announcement-plan.json'));
aassert.ok(html.includes('lineSending:false'));
aassert.ok(html.includes('pushNotification:false'));
aassert.ok(html.includes('erp-data-adapter.js'));
aassert.ok(html.includes('erp-engine.js'));
aassert.ok(html.includes('erp-calculator-center.js'));
aassert.ok(html.includes('erp-alert-center.js'));
aassert.ok(html.includes('map-display-center.js'));
aassert.ok(html.includes('erp-admin-master-data.js'));
aassert.ok(html.includes('localEdits'));
aassert.ok(html.includes('workbookHash'));
aassert.ok(html.includes('hashPayload'));
aassert.ok(html.includes('REQUIRED_SHEET_COUNT'));
aassert.ok(html.includes('sheetReadinessPackage'));
aassert.ok(html.includes('downloadSheetReadiness'));
aassert.ok(html.includes('missingRequiredSheets'));
aassert.ok(html.includes('draftPackage'));
aassert.ok(html.includes('candidatePublishedSchedule'));
aassert.ok(html.includes('ADMIN_FILE_REGISTRY'));
aassert.ok(html.includes('adminAuditPackage'));
aassert.ok(html.includes('downloadAdminAudit'));
aassert.ok(html.includes('adminCutoverPlanPackage'));
aassert.ok(html.includes('downloadAdminCutoverPlan'));
aassert.ok(html.includes('sl-transit-admin-cutover-plan.json'));
aassert.ok(html.includes('legacy-project-removal'));
aassert.ok(html.includes('future-publish'));
aassert.ok(html.includes('auditEvents'));
aassert.ok(html.includes('recordAudit'));
aassert.ok(html.includes('auditLogPackage'));
aassert.ok(html.includes('downloadLocalAuditLog'));
aassert.ok(html.includes('sl-transit-admin-local-audit-log.json'));
aassert.ok(html.includes('eventCount'));
aassert.ok(html.includes('REVIEW_ARTIFACTS'));
aassert.ok(html.includes('FUTURE_RULE_REQUIREMENTS'));
aassert.ok(html.includes('rulesRequirementsPackage'));
aassert.ok(html.includes('downloadRulesRequirements'));
aassert.ok(html.includes('releaseManifest'));
aassert.ok(html.includes('downloadReleaseManifest'));
aassert.ok(html.includes('readinessSummaryPackage'));
aassert.ok(html.includes('downloadReadinessSummary'));
aassert.ok(html.includes('sl-transit-admin-readiness-summary.json'));
aassert.ok(html.includes('waitingModules'));
aassert.ok(html.includes('artifactCount'));
aassert.ok(html.includes('backupRollbackDrillPackage'));
aassert.ok(html.includes('downloadBackupRollbackDrill'));
aassert.ok(html.includes('sl-transit-admin-backup-rollback-drill.json'));
aassert.ok(html.includes('rollbackApplied:false'));
aassert.ok(html.includes('ownerPublishGatePackage'));
aassert.ok(html.includes('downloadOwnerPublishGate'));
aassert.ok(html.includes('sl-transit-admin-owner-publish-gate.json'));
aassert.ok(html.includes('applyButton:false'));
aassert.ok(html.includes('futureApplyContract'));
aassert.ok(html.includes('requiredGates'));
aassert.ok(html.includes('readyForApplyStillFalse'));
aassert.ok(html.includes('ownerHandoffChecklistPackage'));
aassert.ok(html.includes('downloadOwnerHandoffChecklist'));
aassert.ok(html.includes('sl-transit-admin-owner-handoff-checklist.json'));
aassert.ok(html.includes('handoffItems'));
aassert.ok(html.includes('safetyCertificationPackage'));
aassert.ok(html.includes('downloadSafetyCertification'));
aassert.ok(html.includes('sl-transit-admin-safety-certification.json'));
aassert.ok(html.includes('forbiddenScopes'));
aassert.ok(html.includes('allowedReadSources'));
aassert.ok(html.includes('configReadinessPackage'));
aassert.ok(html.includes('downloadConfigReadiness'));
aassert.ok(html.includes('sl-transit-admin-config-readiness.json'));
aassert.ok(html.includes('readyForLiveRead'));
aassert.ok(html.includes('missingFields'));
aassert.ok(html.includes('firebaseConfigFile'));
aassert.ok(html.includes('readFirebaseConfig'));
aassert.ok(html.includes('applyFirebaseConfig'));
aassert.ok(html.includes('local browser memory only'));
aassert.ok(html.includes("cfg.projectId!=='sl-transit-9464e'"));
aassert.ok(html.includes('goLiveReadinessPackage'));
aassert.ok(html.includes('downloadGoLiveReadiness'));
aassert.ok(html.includes('sl-transit-admin-go-live-readiness.json'));
aassert.ok(html.includes('remainingDecisions'));
aassert.ok(html.includes('readyForProduction'));
aassert.ok(html.includes('ROLE_ACCESS_MATRIX'));
aassert.ok(html.includes('roleAccessMatrixPackage'));
aassert.ok(html.includes('downloadRoleAccessMatrix'));
aassert.ok(html.includes('sl-transit-admin-role-access-matrix.json'));
aassert.ok(html.includes('userRoleMutation:false'));
aassert.ok(html.includes('releaseEvidence'));
aassert.ok(html.includes('releaseEvidencePackage'));
aassert.ok(html.includes('releaseEvidencePanel'));
aassert.ok(html.includes('saveReleaseEvidence'));
aassert.ok(html.includes('downloadReleaseEvidence'));
aassert.ok(html.includes('sl-transit-admin-release-evidence.json'));
aassert.ok(html.includes('backupRef'));
aassert.ok(html.includes('rollbackNote'));
aassert.ok(html.includes('rulesReviewRef'));
aassert.ok(html.includes('reviewArtifacts'));
aassert.ok(html.includes('reviewBundle'));
aassert.ok(html.includes('downloadReviewBundle'));
aassert.ok(html.includes('publishPlan'));
aassert.ok(html.includes('releaseAssessment'));
aassert.ok(html.includes('readinessScore'));
aassert.ok(html.includes('blockedReasons'));
aassert.ok(html.includes('applyAllowed:false'));
aassert.ok(html.includes('releaseChecks'));
aassert.ok(html.includes('ownerDecision'));
aassert.ok(html.includes('ownerDecisionPanel'));
aassert.ok(html.includes('saveOwnerDecision'));
aassert.ok(html.includes('approved_for_future_apply'));
aassert.ok(html.includes('ownerApproval'));
aassert.ok(html.includes('freshBackup'));
aassert.ok(html.includes('rollbackPlan'));
aassert.ok(html.includes('firebaseRulesReview'));
aassert.ok(html.includes('data-release-check'));
aassert.ok(html.includes('sl-transit-admin-draft-package.json'));
aassert.ok(html.includes('sl-transit-admin-file-audit.json'));
aassert.ok(html.includes('sl-transit-admin-rules-requirements.json'));
aassert.ok(html.includes('sl-transit-admin-center-status.json'));
aassert.ok(html.includes('sl-transit-admin-candidate-publishedSchedule.json'));
aassert.ok(html.includes('sl-transit-admin-sheet-readiness.json'));
aassert.ok(html.includes('sl-transit-admin-release-manifest.json'));
aassert.ok(html.includes('sl-transit-admin-review-bundle.json'));
aassert.ok(html.includes('sl-transit-admin-blocked-publish-plan.json'));
aassert.ok(html.includes("publicationStatus:'review_candidate_blocked'"));
aassert.ok(html.includes('containsOperationalPrivateData:false'));
aassert.ok(html.includes('deployRules:false'));
aassert.ok(html.includes('mustNotDeployFromConsole:true'));
aassert.ok(html.includes("primaryFile: 'admin-erp.html'"));
aassert.ok(html.includes("legacyFile: 'admin.html'"));
aassert.ok(html.includes("compatibilityRedirect: 'admin-console.html'"));
aassert.ok(html.includes("['admin-erp.html','primary Admin Console'"));
aassert.ok(html.includes("['admin.html','legacy redirect'"));
aassert.ok(html.includes("['admin-console.html','compatibility redirect'"));
aassert.ok(html.includes('FLOW_STEPS'));
aassert.ok(html.includes('Excel'));
aassert.ok(html.includes('Draft'));
aassert.ok(html.includes('Review'));
aassert.ok(html.includes('Publish'));
aassert.ok(legacyAdmin.includes('url=admin-erp1.html'));
aassert.ok(compatibilityAdmin.includes('url=admin-erp1.html'));

console.log('admin-erp safety ok');
