const assert = require('assert');
const policy = require('../functions/admin-erp-authorization.js');
const owner = policy.accessFor({ uid: 'owner' }, { role: 'owner' });
const admin = policy.accessFor({ uid: 'admin' }, { role: 'admin' });
const viewer = policy.accessFor({ uid: 'viewer' }, { role: 'viewer' });
const operations = policy.accessFor({ uid: 'operations' }, { role: 'operations' });
const finance = policy.accessFor({ uid: 'finance' }, { role: 'finance' });
assert(!policy.accessFor(null, { role: 'owner' }).authenticated);
assert(owner.can('publish')); assert(owner.can('rollback')); assert(admin.can('edit')); assert(!admin.can('publish')); assert(viewer.can('read')); assert(!viewer.can('edit'));
assert(operations.can('edit')); assert(!operations.can('publish')); assert(finance.can('review')); assert(!finance.can('rollback'));
assert.strictEqual(policy.normalizeAccount(true).legacyBoolean, true);
const scoped = policy.sanitizeReadModel({ stops: { s1: {} }, adminAccounts: { owner: true }, fleet: { vehicles: { v1: { vehicleId: 'v1', driverPhone: 'private' } }, drivers: { d1: { phone: 'private' } } } }, owner);
assert(scoped.stops); assert(scoped.fleet.vehicles); assert(!scoped.adminAccounts); assert(!scoped.fleet.drivers);
assert(!scoped.fleet.vehicles.v1.driverPhone);
const accountRows = policy.sanitizeAdminAccounts({ owner: { role: 'owner', email: 'must-not-leak@example.test', displayNameTh: 'เจ้าของระบบ' } });
assert.strictEqual(accountRows.owner.role, 'owner');
assert(accountRows.owner.permissions.includes('manage_users'));
assert.strictEqual(Object.prototype.hasOwnProperty.call(accountRows.owner, 'email'), false);
assert.strictEqual(policy.workflowTransition('draft', 'submit_for_review', admin).to, 'in_review');
assert.strictEqual(policy.workflowTransition('approved', 'publish', admin).code, 'permission_denied');
assert.strictEqual(policy.workflowTransition('approved', 'publish', admin, { ownerApproved: true }).to, 'published');
assert.strictEqual(policy.workflowTransition('published', 'rollback', owner).to, 'rolled_back');
console.log('admin-erp authorization: PASS');
