const assert = require('assert');
const fs = require('fs');
const path = require('path');

const booking1 = fs.readFileSync(path.join(__dirname, '..', 'booking1.html'), 'utf8');
const adapter = fs.readFileSync(path.join(__dirname, '..', 'booking1-preview-adapter.js'), 'utf8');
const bridge = fs.readFileSync(path.join(__dirname, '..', 'booking-bridge.js'), 'utf8');
const calculator = fs.readFileSync(path.join(__dirname, '..', 'erp-calculator-center.js'), 'utf8');
const rules = fs.readFileSync(path.join(__dirname, '..', 'database.rules.json'), 'utf8');
const databaseRules = JSON.parse(rules).rules;
const identityCenter = fs.readFileSync(path.join(__dirname, '..', 'passenger-identity-center.js'), 'utf8');

function pageAncestors(html) {
  const re = /<\/?div\b[^>]*>/gi;
  const stack = [];
  const pages = {};
  let match;
  while ((match = re.exec(html))) {
    const tag = match[0];
    if (/^<\/div/i.test(tag)) {
      stack.pop();
      continue;
    }
    const idMatch = tag.match(/\bid=["']([^"']+)/i);
    const classMatch = tag.match(/\bclass=["']([^"']+)/i);
    const item = {
      id: idMatch ? idMatch[1] : '',
      cls: classMatch ? classMatch[1] : '',
      ancestors: stack.map((entry) => entry.id || entry.cls || 'div').filter(Boolean)
    };
    stack.push(item);
    if (/^page[1-4]$/.test(item.id)) pages[item.id] = item.ancestors;
  }
  return pages;
}

assert(bridge.includes("var PREVIEW_BASE_PATH = 'publishedSchedule'"), 'Booking1 bridge must use publishedSchedule');
assert(bridge.includes(".child('originOptions').once('value')"), 'Booking1 must read originOptions as lightweight initial data');
assert(bridge.includes(".child('destinationOptionsByOrigin').once('value')"), 'Booking1 must read destinationOptionsByOrigin as lightweight initial data');
assert(bridge.includes(".child('paymentContact').once('value')"), 'Booking1 must read payment contact from publishedSchedule paymentContact');
assert(bridge.includes(".child('bookingPolicy').once('value')"), 'Booking1 must read seat/service-fee policy from ERP Data Center');
assert(bridge.includes(".child('pairs').child(storageKey).once('value')"), 'Booking1 must lazy-load only the selected pair');
assert(!/db\.ref\(['"]publishedSchedule['"]\)\.once\s*\(/.test(bridge + booking1), 'Booking1 must not once-read full publishedSchedule');
assert(!/db\.ref\(['"]publishedSchedule['"]\)\.on\s*\(/.test(bridge + booking1), 'Booking1 must not subscribe to full publishedSchedule');
assert(!bridge.includes("db.ref('routeData')"), 'Booking1 bridge must not read legacy routeData');
assert(!bridge.includes('SLTransitCatalog.loadPublished'), 'Booking1 bridge must not load legacy publishedCatalog');
assert(!bridge.includes('LEG2_DEST'), 'Booking1 bridge must not use static leg2 destination/fare table');
assert(!bridge.includes('TRANSFER_BUFFER'), 'Booking1 bridge must not use static transfer buffers');
assert(!bridge.includes('|| 55'), 'Booking1 bridge must not hardcode 55-baht fare fallback');
assert(booking1.includes('booking-availability-center.js'), 'Booking1 must load Booking Availability Center');
assert(booking1.includes('fare-decision-center.js'), 'Booking1 must load Fare Decision Center');
assert(booking1.includes('erp-calculator-center.js'), 'Booking1 must load ERP Calculator Center for trip recommendation ordering');
assert(booking1.includes('https://static.line-scdn.net/liff/edge/2/sdk.js'), 'Booking1 must load the official LINE LIFF SDK for optional passenger login');
assert(booking1.includes('window.SL_TRANSIT_LINE_LIFF_ID = window.SL_TRANSIT_LINE_LIFF_ID ||'), 'Booking1 must expose a single LIFF ID config slot');
assert(booking1.includes('2010733143-xQFRzCsR'), 'Booking1 must configure the owner-provided LIFF ID');
assert(booking1.includes('passenger-identity-center.js'), 'Booking1 must load Passenger Identity Center before creating bookings');
assert(booking1.includes('lineLoginBtn'), 'Booking1 passenger form must expose optional LINE login');
assert(booking1.includes('loginBookingLineIdentity(event)'), 'Booking1 LINE login button must delegate to the preview adapter');
assert(!booking1.includes('booking-pos.js'), 'Booking1 must not load booking POS/runtime writes');
assert(!booking1.includes('booking-capacity.js'), 'Booking1 must not load booking capacity runtime reads');
assert(!booking1.includes('catalog-engine.js'), 'Booking1 must not load legacy catalog engine');
assert(!booking1.includes('schedule-engine.js'), 'Booking1 must not load legacy schedule engine');
assert(!booking1.includes('firebase-auth-compat.js'), 'Booking1 must not initialize Firebase Auth');
assert(!booking1.includes('firebase-storage-compat.js'), 'Booking1 must not initialize Firebase Storage');
assert(!booking1.includes("ref('announcements')"), 'Booking1 must not read direct announcements outside ERP contract');
assert(!booking1.includes("ref('settings')"), 'Booking1 must not read direct settings outside ERP contract');
assert(!booking1.includes("ref('bookings')"), 'Booking1 must not read direct bookings');
assert(!booking1.includes('signInAnonymously'), 'Booking1 must not sign in anonymously');
assert(!booking1.includes('SLBookingCapacity'), 'Booking1 must not reference booking capacity runtime');
assert(!booking1.includes('SLBookingPOS'), 'Booking1 must not reference booking POS runtime');
assert(!booking1.includes('POS'), 'Booking1 must not keep POS layer references');
assert(bridge.includes('SLTransitBookingAvailabilityCenter'), 'Booking1 bridge must ask Booking Availability Center for eligibility');
assert(bridge.includes('SLTransitFareDecisionCenter'), 'Booking1 bridge must ask Fare Decision Center for fares');
assert(bridge.includes('SLTransitCalculatorCenter.recommendedBookingTrips'), 'Booking1 bridge must ask ERP Calculator Center for recommended trip ordering');
assert(calculator.includes('function recommendedBookingTrips'), 'ERP Calculator Center must own Booking1 trip recommendation logic');
assert(calculator.includes('function calculateBookingTotal'), 'ERP Calculator Center must own Booking1 total calculation');
assert(adapter.includes('calculator.calculateBookingTotal'), 'Booking1 adapter must delegate totals to ERP Calculator Center');
assert(!adapter.includes('base * n') && !adapter.includes('SERVICE_FEE_AMOUNT * n'), 'Booking1 adapter must not calculate fare or service fee locally');
assert(bridge.includes('getBookingSeatLimit'), 'Booking1 must obtain the seat limit through the ERP Data Center bridge');
assert(!booking1.includes('Math.min(10'), 'Booking1 must not hardcode a ten-seat maximum');
assert(!booking1.includes('แปดริ้ว'), 'Booking1 must not hardcode the transfer point label');
assert(bridge.includes("info.source = 'erp_data_center'"), 'Booking1 transfer display data must be marked as ERP Data Center output');
assert(bridge.includes('selectionAllowed: availabilityDecision.selectionAllowed === true'), 'Booking1 bridge must expose selectionAllowed separately from bookingAllowed');
assert(!bridge.includes('function _extractFare'), 'Booking1 bridge must not calculate fare locally');
assert(!bridge.includes('function _pairIsExternal'), 'Booking1 bridge must not decide external/reference status locally');

assert(booking1.includes('booking1-preview-adapter.js'), 'Booking1 must load the preview adapter');
assert(booking1.includes('booking1-preview-adapter.js?v=20260716a'), 'Booking1 must bust cached preview adapter versions after payment-step layout fixes');
assert(booking1.includes('var global = window;'), 'Booking1 inline scripts must use a browser-safe global alias');
assert.deepStrictEqual(pageAncestors(booking1), { page1: [], page2: [], page3: [], page4: [] }, 'Booking1 pages must be sibling roots so page navigation cannot hide active pages inside inactive parents');
assert(booking1.includes('function sanitizePhone'), 'Booking1 must define phone sanitizer for passenger form');
assert(booking1.includes('function isValidThaiPhone'), 'Booking1 must define Thai phone validator for passenger form');
assert(booking1.includes('global.sanitizePhone = sanitizePhone'), 'Booking1 must expose phone sanitizer to the preview adapter');
assert(booking1.includes('global.isValidThaiPhone = isValidThaiPhone'), 'Booking1 must expose phone validator to the preview adapter');
assert(booking1.includes('id="search-pax-count"'), 'Booking1 search passenger field must expose a live passenger count');
assert(booking1.includes('onclick="openPaxPicker()"'), 'Booking1 search passenger field must open a passenger count picker');
assert(booking1.includes('function openPaxPicker'), 'Booking1 must implement passenger count picker selection');
assert(booking1.includes('function selectPaxCount'), 'Booking1 must select passenger count directly from the picker');
assert(booking1.includes('window.openPaxPicker      = openPaxPicker'), 'Booking1 must expose passenger count picker for inline handlers');
assert(!booking1.includes('search-pax-btn'), 'Booking1 search passenger field must not render plus/minus buttons');
assert(booking1.includes("searchPaxEl.textContent = state.pax + ' คน ▾'"), 'Booking1 passenger count changes must sync the search passenger field');
assert(booking1.includes('var PUBLIC_BOOKING_PAX_LIMIT = 10'), 'Booking1 must mirror the public Firebase pax safety limit in the UI');
assert(adapter.includes('global.PUBLIC_BOOKING_PAX_LIMIT'), 'Booking1 adapter totals must apply the public pax safety limit');
assert(booking1.includes('window.showPage           = showPage'), 'Booking1 must expose page navigation to the preview adapter');
assert(booking1.includes('window.selectPayMethod    = selectPayMethod'), 'Booking1 must expose payment method reset to the preview adapter');
assert(booking1.includes('goToTicket();'), 'Booking1 confirm button must delegate submit to the ERP preview adapter booking flow');
assert(booking1.includes('id="pm-onsite"'), 'Booking1 must offer pay-on-site booking');
assert(booking1.includes("selectPayMethod('onsite')"), 'Booking1 must default to pay-on-site when no transfer method is selected');
assert(!booking1.includes('id="terms-check"'), 'Booking1 must not keep a duplicate terms checkbox on the passenger page');
assert(!adapter.includes('terms-check'), 'Booking1 adapter must not require the removed duplicate terms checkbox');
assert(!booking1.includes('page2PaymentMount'), 'Booking1 must keep passenger and payment pages separated');
assert(!booking1.includes('mergePaymentIntoPassengerPage'), 'Booking1 must not move payment DOM into the passenger page');
assert(adapter.includes('global.showPage(3)'), 'Booking1 adapter must keep the separate payment page after passenger details');
assert(adapter.includes('function enforceSeparatePaymentStep'), 'Booking1 adapter must repair cached merged payment markup back into the payment page');
assert(adapter.includes("document.getElementById('page2PaymentMount')"), 'Booking1 adapter must recognize the old merged payment mount from cached markup');
assert(bridge.includes('getPaymentContact: getPaymentContact'), 'Booking1 bridge must expose ERP payment contact');
assert(booking1.includes('SLBookingBridge.getPaymentContact'), 'Booking1 must consume payment contact through the bridge');
assert(booking1.includes('232-8-93015-6'), 'Booking1 must show the owner-provided account number fallback until ERP publishes paymentContact');
assert(booking1.includes('082-9860032'), 'Booking1 must show the owner-provided phone fallback until ERP publishes paymentContact');
assert(!booking1.includes('xxx-x-xxxxx-x'), 'Booking1 must not show the placeholder account number');
assert(!booking1.includes('trip-check'), 'Booking1 trip cards must not render the old green selected check icon');
assert(!booking1.includes('SLBookingCapacity.requestRouteContinue'), 'Booking1 trip buttons must not use legacy capacity continuation');
assert(booking1.includes('href="info.html#policy"'), 'Booking1 booking terms link must point to info policy section');
assert(booking1.includes('href="info.html#privacy"'), 'Booking1 service policy link must point to info privacy section');
assert(!booking1.includes('href="#" onclick="openConsentPopup(event)">เงื่อนไขการจอง'), 'Booking1 terms link must not be a dead # link');
assert(adapter.includes('SLBookingBridge.getBookableStops()'), 'Origin picker must use bridge originOptions');
assert(adapter.includes('SLBookingBridge.getDestinationOptions(state.originKey)'), 'Destination picker must use origin-scoped destinationOptionsByOrigin');
assert(!adapter.includes('/preview/publishedSchedule'), 'Booking1 UI text must not point users to preview publishedSchedule');
assert(!adapter.includes('ERP Preview'), 'Booking1 UI text must not call active schedule data ERP Preview');
assert(adapter.includes('s.group || null'), 'Destination picker must render ERP-provided destination option groups');
assert(adapter.includes('stopPickerItemsHtml'), 'Destination picker must use grouped picker rendering');
assert(adapter.includes('esc(group)'), 'Destination group labels must come from ERP option.group');
assert(adapter.includes('SLBookingBridge.loadAvailableTrips'), 'Trip cards must lazy-load selected pair data');
assert(bridge.includes('Array.isArray(pair.connectionOptions)'), 'Booking1 bridge must read ERP connectionOptions for transfer-reference timetable rows');
assert(bridge.includes('function _transferInfo'), 'Booking1 bridge must normalize ERP transfer display metadata');
assert(bridge.includes('firstLeg.toLabel'), 'Booking1 bridge must use ERP pair segment labels for transfer points');
assert(bridge.includes('timeEntry.nextDepartureTime'), 'Booking1 bridge must pass ERP connection next departure time to Booking1');
assert(!adapter.includes('recommendedBookingTrips'), 'Booking1 adapter must not own recommendation logic');
assert(!adapter.includes('minutesFromTime'), 'Booking1 adapter must not compare trip times locally');
assert(adapter.includes('function transferPointText'), 'Booking1 adapter must render ERP-provided transfer point text');
assert(adapter.includes('function transferDetailHtml'), 'Booking1 adapter must render ERP-provided transfer details');
assert(adapter.includes('routeText(trip)'), 'Booking1 compact cards must render route text per ERP trip');
assert(adapter.includes('routeText(best)'), 'Booking1 recommended card must render route text per ERP trip');
assert(adapter.includes('!trip.selectionAllowed'), 'Booking1 adapter must use selectionAllowed for the trip select button');
assert(!adapter.includes('trip-check'), 'Booking1 adapter trip cards must not render the old green selected check icon');
assert(adapter.includes('selected.selectionAllowed'), 'Booking1 adapter must let selected ERP trips continue to passenger/payment pages');
assert(!adapter.includes('selected.bookingAllowed'), 'Booking1 adapter page navigation must not be blocked by production bookingAllowed');
assert(adapter.includes('selected.fareMissing'), 'Booking1 adapter must block/report missing fare contract');
assert(adapter.includes('selected.externalPaymentRequired'), 'Booking1 adapter must block external-pay fare collection');
assert(bridge.includes('liveTrackingAvailable: false'), 'Booking1 bridge must keep schedule-only/no-live-tracking state internally');
assert(adapter.includes("db.ref('bookings/' + booking.code).set(booking)"), 'Booking1 adapter must create real legacy bookings/{code} records');
assert(rules.includes("newData.child('source').val() === 'booking1.html'"), 'Firebase rules must allow validated Booking1 public legacy booking creates');
assert(rules.includes("newData.child('sourceMode').val() === 'erp_data_center'"), 'Booking1 booking writes must stay ERP Data Center scoped in Firebase rules');
assert(rules.includes("newData.child('publishedSchedule').child('readyForApply').val() === false"), 'Booking1 public booking rule must preserve preview publishedSchedule marker validation');
assert(rules.includes("newData.child('paymentStatus').val() === 'slip_uploaded' && newData.child('slipUploaded').val() === true"), 'Booking1 public booking rule must allow uploaded-slip payment status');
assert(rules.includes("newData.child('paymentStatus').val() === 'awaiting_payment' && newData.child('slipUploaded').val() === false"), 'Booking1 public booking rule must keep non-slip bookings awaiting payment');
assert(rules.includes("newData.child('paymentStatus').val() === 'pay_on_site' && newData.child('slipUploaded').val() === false && newData.child('paymentMode').val() === 'onsite'"), 'Booking1 public booking rule must allow validated pay-on-site bookings');
assert(databaseRules.bookings['$bookingId']['.write'].includes("source').val() === 'booking1.html'"), 'Booking1 public create rule must be on legacy top-level bookings/{code}');
assert.strictEqual(databaseRules.operations.bookings['$bookingId']['.write'], 'auth != null', 'operations/bookings must remain auth-only');
assert(adapter.includes('legacyBookingPayload'), 'Booking1 adapter must map ERP snapshot to legacy booking payload for check_ticket/passenger compatibility');
assert(adapter.includes("snapshot.payMethod === 'onsite' ? 'pay_on_site'"), 'Booking1 adapter must map onsite bookings to pay_on_site payment status');
assert(adapter.includes('function withoutUndefined'), 'Booking1 adapter must remove undefined fields before Firebase writes');
assert(adapter.includes('withoutUndefined(legacyBookingPayload'), 'Booking1 real booking payload must be sanitized before Firebase set');
assert(!adapter.includes('* (snapshot.pax || 1)'), 'Booking1 real booking payload must not multiply fare locally');
assert(!adapter.includes('snapshot.fareAmount || 0'), 'Booking1 real booking payload must not fall back to local fareAmount arithmetic');
assert(adapter.includes("throw new Error('booking_total_not_ready')"), 'Booking1 real booking payload must fail closed when Calculator Center total is not ready');
assert(adapter.includes("sourceMode: 'erp_data_center'"), 'Booking1 real booking payload must record ERP Data Center source mode');
assert(adapter.includes('SLTransitPassengerIdentityCenter'), 'Booking1 adapter must use Passenger Identity Center for optional LINE login');
assert(adapter.includes('global.loginBookingLineIdentity'), 'Booking1 adapter must expose optional LINE login handler');
assert(adapter.includes('LINE_LOGIN_PENDING_KEY'), 'Booking1 adapter must persist selected booking state before LINE redirects');
assert(adapter.includes('savePendingLineBookingState(state)'), 'Booking1 LINE login must save selected trip before redirecting to LINE');
assert(adapter.includes('resumePendingLineLogin()'), 'Booking1 adapter must resume LINE login after trip data reloads');
assert(adapter.includes('completeLineLogin'), 'Booking1 adapter must complete LINE login without forcing another redirect');
assert(adapter.includes('showPaymentPageAfterLineIdentity'), 'Booking1 LINE login and redirect resume must share the payment continuation flow');
assert(adapter.includes('guestPassengerIdentity(state.name, state.phone)'), 'Guest bookings must keep manual passenger identity');
assert(adapter.includes('lineNotificationPreference()'), 'LINE bookings must opt in to LINE ticket/trip notifications');
assert(adapter.includes('passengerIdentity: currentPassengerIdentity(state)'), 'Booking1 snapshot must include passenger identity');
assert(adapter.includes('notificationPreference: currentNotificationPreference(state)'), 'Booking1 snapshot must include notification preference');
assert(adapter.includes('consent: currentConsent(state)'), 'Booking1 snapshot must include consent evidence');
assert(bridge.includes('passengerIdentity: params.passengerIdentity || null'), 'Booking bridge must preserve passenger identity in snapshots');
assert(bridge.includes('notificationPreference: params.notificationPreference || null'), 'Booking bridge must preserve notification preference in snapshots');
assert(bridge.includes('consent: params.consent || null'), 'Booking bridge must preserve consent evidence in snapshots');
assert(identityCenter.includes('LINE_LOGIN_NOT_CONFIGURED'), 'Passenger Identity Center must fail closed until a LIFF ID is configured');
assert(identityCenter.includes('completeLineLogin'), 'Passenger Identity Center must support completing a LIFF redirect without starting a new login');
assert(identityCenter.includes("provider: 'guest'"), 'Passenger Identity Center must support non-login guest identity');
assert(identityCenter.includes("provider: 'line'"), 'Passenger Identity Center must support LINE passenger identity');
assert(!identityCenter.includes('getAccessToken'), 'Passenger Identity Center must not store LINE access tokens in bookings');
assert(adapter.includes('var transfer = transferPoint(state);'), 'Booking1 legacy payload must define transfer point before writing it');
assert(!adapter.includes('No live vehicle tracking'), 'Booking1 adapter must not show no-live-tracking technical text to passengers');
assert(!adapter.includes('schedule only'), 'Booking1 adapter must not show schedule-only technical text to passengers');
assert(!adapter.includes('ERP Data Center pair:'), 'Booking1 adapter must not show ERP pair technical text to passengers');
assert(!adapter.includes('SLBookingCapacity.requestRouteContinue'), 'Booking1 adapter trip selection must not use legacy capacity continuation');
assert(!adapter.includes('= 55'), 'Booking1 adapter must not fabricate 55-baht fare');
assert(!adapter.includes("= '09:00'"), 'Booking1 adapter must not fabricate default 09:00 trips');
assert(!bridge.includes('.sort(function'), 'Booking1 bridge must preserve ERP option order instead of sorting locally');
assert(booking1.includes('background: #fff7ed; color: #d97706;'), 'Booking1 soon badges must keep orange styling');
assert(booking1.includes('.trip-transfer-detail'), 'Booking1 must include trip transfer detail styling');

assert(!booking1.includes('ยังไม่เปิดสร้าง booking จริง'), 'Booking1 submit guard must not block real booking creation');

console.log('booking1 preview data contract ok');
