const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const booking = fs.readFileSync(path.join(root, 'booking.html'), 'utf8');
const booking1 = fs.readFileSync(path.join(root, 'booking1.html'), 'utf8');
const checkTicket = fs.readFileSync(path.join(root, 'check_ticket.html'), 'utf8');
const trackTrip = fs.readFileSync(path.join(root, 'track_trip.html'), 'utf8');
const cancelTicket = fs.readFileSync(path.join(root, 'cancel_ticket.html'), 'utf8');

assert(index.includes('href="track_trip.html"'), 'Home tracking entry must use track_trip.html');
assert(index.includes('href="cancel_ticket.html"'), 'Home cancel entry must use cancel_ticket.html');
assert(index.includes('ติดตามรถของฉัน<br>สำหรับตั๋วที่จองแล้ว'), 'Home tracking label must be passenger tracking language');
assert(booking1.includes('href="track_trip.html"'), 'Booking1 menu must use track_trip.html');
assert(booking1.includes('href="cancel_ticket.html"'), 'Booking1 menu must use cancel_ticket.html');
assert(booking1.includes('ติดตามรถได้ทันที'), 'Booking1 benefit copy must use tracking language');
assert(booking.includes('booking1.html'), 'Legacy booking entry must redirect users to Booking1');
assert(!booking.includes('track_trip.html?code='), 'Legacy booking entry must not own QR/check-in tracking links');
assert(booking1.includes('track_trip.html?code='), 'Booking1 QR link must open tracking entry');
assert(checkTicket.includes('<title>ติดตามรถของฉัน'), 'Underlying ticket page must use passenger tracking title');
assert(checkTicket.includes('<h1>ติดตามรถของฉัน</h1>'), 'Underlying ticket page must use passenger tracking heading');
assert(trackTrip.includes("params.set('entry', 'track')"), 'track_trip.html must force tracking entry mode');
assert(trackTrip.includes("window.location.replace('check_ticket.html' + (query ? '?' + query : '') + hash)"), 'track_trip.html must preserve tracking query parameters');
assert(!cancelTicket.includes('http-equiv="refresh"'), 'cancel_ticket.html must be a real cancellation entry page, not only a meta redirect');
assert(cancelTicket.includes('lookupTicket'), 'cancel_ticket.html must expose its own cancellation lookup form');
assert(!cancelTicket.includes("window.location.replace('check_ticket.html"), 'cancel_ticket.html must not redirect into the tracking page');
assert(!cancelTicket.includes('mapbox'), 'cancel_ticket.html must not load map dependencies');
assert(!cancelTicket.includes('trackingMap'), 'cancel_ticket.html must not render a tracking map');
assert(cancelTicket.includes('id="ticketCard"'), 'cancel_ticket.html must show a ticket-style booking card');
assert(cancelTicket.includes('id="cancelButton"'), 'cancel_ticket.html must provide a cancellation action');
assert(cancelTicket.includes('href="index.html"'), 'cancel_ticket.html must provide a home-page return link');
assert(checkTicket.includes("var PAGE_ENTRY_MODE = 'track'"), 'Check Ticket must default to tracking mode');
assert(checkTicket.includes("show('cancelPanel', PAGE_ENTRY_MODE === 'cancel')"), 'Tracking mode must not show the cancellation panel');
assert(checkTicket.includes("show('cancelTicketButton', PAGE_ENTRY_MODE === 'cancel')"), 'Tracking map must not show the cancellation button unless opened from cancellation entry');
assert(checkTicket.includes("if (PAGE_ENTRY_MODE === 'cancel')"), 'Cancellation entry mode must branch before tracking layout');
assert(checkTicket.includes("show('trackingPage', false)"), 'Cancellation entry mode must keep the map/tracking page hidden');
assert(checkTicket.includes('href="index.html"'), 'Cancellation flow must provide a home-page return link');

console.log('tracking/cancel routing ok');
